# Generated by Django 5.0.6 on 2024-08-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_professor_category'),
        ('group', '0002_group_subjects_alter_group_career_alter_group_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='academy.student', verbose_name='Estudiantes'),
        ),
    ]
