# Generated by Django 5.0.6 on 2024-08-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_subject_failed', models.IntegerField()),
                ('m1_p1', models.BooleanField(default=False)),
                ('m1_p2', models.BooleanField(default=False)),
                ('m1_p3', models.BooleanField(default=False)),
                ('m1_p4', models.BooleanField(default=False)),
                ('m2_p1', models.BooleanField(default=False)),
                ('m2_p2', models.BooleanField(default=False)),
                ('m2_p3', models.BooleanField(default=False)),
                ('m2_p4', models.BooleanField(default=False)),
                ('m3_p1', models.BooleanField(default=False)),
                ('m3_p2', models.BooleanField(default=False)),
                ('m3_p3', models.BooleanField(default=False)),
                ('m3_p4', models.BooleanField(default=False)),
                ('m4_p1', models.BooleanField(default=False)),
                ('m4_p2', models.BooleanField(default=False)),
                ('m4_p3', models.BooleanField(default=False)),
                ('m4_p4', models.BooleanField(default=False)),
                ('m5_p1', models.BooleanField(default=False)),
                ('m5_p2', models.BooleanField(default=False)),
                ('m5_p3', models.BooleanField(default=False)),
                ('m5_p4', models.BooleanField(default=False)),
                ('m6_p1', models.BooleanField(default=False)),
                ('m6_p2', models.BooleanField(default=False)),
                ('m6_p3', models.BooleanField(default=False)),
                ('m6_p4', models.BooleanField(default=False)),
                ('m7_p1', models.BooleanField(default=False)),
                ('m7_p2', models.BooleanField(default=False)),
                ('m7_p3', models.BooleanField(default=False)),
                ('m7_p4', models.BooleanField(default=False)),
                ('inasistencias', models.BooleanField(default=False)),
                ('Incumplimiento_de_entregables', models.BooleanField(default=False)),
                ('Poco_Interés_en_las_Asignaturas_con_problemas', models.BooleanField(default=False)),
                ('Emocionales_o_Psicológicos', models.BooleanField(default=False)),
                ('Carta_compromiso', models.BooleanField(default=False)),
                ('Problemas_Familiares', models.BooleanField(default=False)),
                ('Bajos_Ingreso', models.BooleanField(default=False)),
                ('Trabaja', models.BooleanField(default=False)),
                ('Padre_o_Madre_de_familia', models.BooleanField(default=False)),
                ('AT_AC_Académico', models.BooleanField(default=False)),
                ('AT_AC_Personal', models.BooleanField(default=False)),
                ('AT_AC_Socioeconómico', models.BooleanField(default=False)),
                ('RT_AR_Académico', models.BooleanField(default=False)),
                ('RT_AR_Personal', models.BooleanField(default=False)),
                ('RT_AR_Socioeconómico', models.BooleanField(default=False)),
                ('Observaciones', models.TextField()),
            ],
        ),
    ]
