# Generated by Django 5.0.6 on 2024-08-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_professor_category'),
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoat',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.student', verbose_name='estudiante'),
            preserve_default=False,
        ),
    ]
