# Generated by Django 5.0.6 on 2024-07-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguimientoAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_subject_failed', models.CharField(blank=True, max_length=3, null=True)),
                ('m1_p1', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
